sonar.projectKey=LastMilePlatform_lastmile-backend-1
sonar.organization=lastmileplatform

sonar.projectName=lastmile-backend-1
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/*.module.ts,**/main.ts,**/*.dto.ts,**/*.entity.ts,**/config/**,**/migrations/**,**/events/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
